import { type NextPage } from "next";
import clsx from "clsx";
import Head from "next/head";
import { Button, FormGroup, Input } from "component";
import { useState } from "react";
import { api } from "~/utils/api";
import { signIn, signOut, useSession } from "next-auth/react";

const Generate: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });

  const session = useSession();

  const isLoggedIn = !!session.data;

  const generateIcon = api.generate.generateIcon.useMutation();

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,
      }));
    };
  }

  async function onSubmit(event: React.FormEvent) {
    event.preventDefault();
    await generateIcon.mutateAsync({
      prompt: form.prompt,
    });
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {!isLoggedIn ? (
          <Button onClick={() => signIn().catch(console.error)}>Login</Button>
        ) : (
          <Button onClick={() => signOut().catch(console.error)}>
            Sign out
          </Button>
        )}
        <form onSubmit={onSubmit} className={clsx("flex flex-col gap-4")}>
          <FormGroup>
            <label>Prompt</label>
            <Input value={form.prompt} onChange={updateForm("prompt")} />
          </FormGroup>
          <input
            className={clsx(
              "bg-blue-400 hover:bg-blue-500",
              "px-4 py-2",
              "rounded"
            )}
            type="submit"
          ></input>
        </form>
      </main>
    </>
  );
};

export default Generate;
