import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrimaryLinkButton } from "~/component";

function HeroBanner() {
  return (
    <section className="mb-24 mt-12 grid grid-cols-1 gap-12 px-8 sm:mt-24 sm:grid-cols-2">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">Generate icons with a click of a button</h1>
        <p className="text-2xl">
          Use AI to generate icons instead of paying a designer and waiting for
          them to create them for you.
        </p>
        <PrimaryLinkButton href="/generate" className="self-start">
          Generated your Icons
        </PrimaryLinkButton>
      </div>
      <Image
        alt="Banner image"
        src="/banner.jpg"
        className="order-first sm:order-none"
        width={400}
        height={300}
      />
    </section>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default Home;
